# Generated by Django 4.2.6 on 2023-11-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_designcategory_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
