# Generated by Django 4.2.6 on 2023-11-02 13:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_request_is_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.AddField(
            model_name='request',
            name='date_create',
            field=models.DateField(default=datetime.datetime(2023, 11, 2, 20, 18, 45, 747217), verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='request',
            name='time_create',
            field=models.TimeField(default=datetime.datetime(2023, 11, 2, 20, 18, 45, 747217), verbose_name='Время создания'),
        ),
    ]
